### PR TITLE
Fixes problem with empty path when there's no pathprefix

### LINKED ISSUE #46: Empty path calculated for first page breaking build
Updated my dependencies (gatsby, plugins etc) to the lastest releases today and am now getting this error at build:

    ERROR #11323
    Your site's "gatsby-node.js" must set the page path when creating a page

It happens on this code:

        createPaginatedPages({
          edges: result.data.allMarkdownRemark.edges,
          createPage: createPage,
          pageTemplate: 'src/templates/index.js',
          pageLength: 20,
        })

Looking at the error - it's the very first page.

Path is calculated in paginate as:

    path:
        typeof buildPath === `function`
          ? buildPath(pageIndex, pathPrefix)
          : buildPaginationRoute(pageIndex, pathPrefix),

Here I am not passing a buildPath function - so that is null and therefore it calls buildPaginationRoute. 

    const buildPaginationRoute = (index, pathPrefix) =>
        index > 1 ? `${pathPrefix}/${index}` : pathPrefix

Index is the empty string on the first page (I think).

So this returns just pathPrefix - but - I am not using pathPrefix for the main index of the site - so that's the empty string.

I suspect that it's related to this change in gatsby:

https://github.com/gatsbyjs/gatsby/commit/44654be688230e530894456891a73a1562acfb9a#diff-c739d0ad63537276e8fc320522a8b985

If you look at the code there you can see that before the change - if the path was the empty string it would do this:

      console.log(chalk.bold.red(message))
      console.log(``)
      console.log(page)

But now it does this:

     report.panic({
        id: `11323`,
        context: {
          pluginName: name,
          pageObject: page,
          message,
        },
      })

If I understood the gatsby code then it means that after this change - it will no longer log and continue but abort a build if we call paginate with no pathPrefix and no buildPath function when creating the first page?

### PR DESCRIPTION
**Pull request by Randyjp**
fixes #46 

We should return an `/` for the homepage when there's no empty path prefix.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -11,8 +11,12 @@ const createGroups = (pages, pageLength) =>
 
 const getPageIndex = index => (index === 0 ? `` : index + 1)
 
-const buildPaginationRoute = (index, pathPrefix) =>
-  index > 1 ? `${pathPrefix}/${index}` : pathPrefix
+const buildPaginationRoute = (index, pathPrefix) => {
+  if (!index && !path) {
```
Comment (janosh) [inline src/index.js]: `path` should actually be `pathPrefix`, no?

File: src/index.js [hunk 2]
```diff
@@ -11,8 +11,12 @@ const createGroups = (pages, pageLength) =>
...
+    return `/`
+  }
+  return index > 1 ? `${pathPrefix}/${index}` : pathPrefix
```
Comment (janosh) [inline src/index.js]: How about we just do
```js
return index > 1 ? `${pathPrefix}/${index}` : (pathPrefix || `/`)
```
and leave out the
```js
if (!index && !path) {
   ...
}
```
check completely?

**Review by janosh — CHANGES_REQUESTED** [review]
Left two comments.

File: src/index.js (hunk 1 above)
Comment (Randyjp) [reply src/index.js]: just noticed, you are right!

File: src/index.js (hunk 2 above)
Comment (Randyjp) [reply src/index.js]: sounds good!

**Comment by Randyjp** [comment]
thanks for the quick review @janosh ;  took care of them!

**Comment by janosh** [comment]
@Randyjp Thanks a lot for this PR
